[phases.setup]
nixPkgs = ['unzip']
cmds = ['curl -fsSL https://bun.sh/install | bash', 'bun install']

[phases.build]
cmd = 'cd packages/cms && bun run build'

[start]
cmd = 'cd packages/cms && bun run start'
