[phases.setup]
nixPkgs = ['unzip']
cmd = 'curl -fsSL https://bun.sh/install | bash'

[phases.install]
cmd = 'bun install'

[phases.build]
cmd = 'cd packages/cms && bun run build'

[start]
cmd = 'cd packages/cms && bun run start'
