# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:1
WORKDIR /usr/src/app

COPY . .
RUN bun install

WORKDIR /usr/src/app/packages/cms
ENV NODE_ENV=production

ARG DATABASE_URL
ARG PAYLOAD_SECRET
ARG PAYLOAD_PUBLIC_DRAFT_SECRET
ARG NEXT_PRIVATE_DRAFT_SECRET
ARG REVALIDATION_KEY
ARG NEXT_PRIVATE_REVALIDATION_KEY
ARG S3_ACCESS_KEY_ID
ARG S3_SECRET_ACCESS_KEY
ARG S3_REGION
ARG S3_BUCKET
ARG S3_ENDPOINT
ARG RESEND_API_KEY
ARG MEILI_ADMIN_KEY
ARG MEILI_URL
ARG OPENAI_API_KEY
ARG NEXT_PUBLIC_SERVER_URL
ARG NEXT_PUBLIC_IS_LIVE
ARG NEXT_PUBLIC_S3_URL
ARG NEXT_PUBLIC_MEILI_URL
ARG NEXT_PUBLIC_MEILI_SEARCH_KEY
ARG NEXT_PUBLIC_MEILI_SEARCH_INDEX

RUN bun run build

RUN chown -R bun:bun /usr/src/app/packages/cms
RUN chmod -R 755 /usr/src/app/packages/cms

# run the app
USER bun
EXPOSE 8080/tcp
ENTRYPOINT [ "bun", "run", "start" ]
